In [2]:
import pdb
import pickle
import numpy as np
import os
from benchmark.datasets import DATASETS
from benchmark.dataset_io import download_accelerated

In [3]:
ds = DATASETS['yfcc-10M']()

In [4]:
# def max_column_length(dataset):
#     max_length = 0
#     for row in dataset:
#         max_length = max(max_length, row.shape[1])
#     return max_length

# # Get the maximum length of columns
# max_len = max_column_length(ds.get_dataset_metadata())
# print("Maximum length of columns across all rows:", max_len)



shapes = np.array([len(np.nonzero(row)[1]) for row in ds.get_dataset_metadata()])

# Find the maximum number of columns across all rows
# max_columns = shapes[:, 1].max()

print("Maximum number of columns across all rows:", max(shapes))

KeyboardInterrupt: 

In [11]:
print(ds.get_dataset().shape)
print(ds.get_dataset_metadata().shape)

print(ds.get_dataset_metadata().nonzero()[0])
print(ds.get_dataset_metadata().nonzero()[1])

print(ds.get_dataset_metadata()[1:10].shape)

val = ds.get_dataset_metadata()[0]
print("##",print(type(val)),val)
print("##", (np.nonzero(val)[1]).shape, len(np.nonzero(val)[1]))
for p in np.nonzero(val)[1]:
    print(p)
print(np.nonzero(val))
print(np.nonzero(ds.get_dataset_metadata()[1]))

(10000000, 192)
(10000000, 200386)
[      0       0       0 ... 9999999 9999999 9999999]
[    6    15    24 ...   345 48730  2841]
(9, 200386)
<class 'scipy.sparse._csr.csr_matrix'>
## None   (0, 6)	1.0
  (0, 15)	1.0
  (0, 24)	1.0
  (0, 89)	1.0
  (0, 337)	1.0
  (0, 443)	1.0
  (0, 442)	1.0
  (0, 441)	1.0
  (0, 440)	1.0
  (0, 439)	1.0
  (0, 438)	1.0
  (0, 437)	1.0
  (0, 436)	1.0
## (13,) 13
6
15
24
89
337
443
442
441
440
439
438
437
436
(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32), array([  6,  15,  24,  89, 337, 443, 442, 441, 440, 439, 438, 437, 436],
      dtype=int32))
(array([0, 0, 0, 0, 0], dtype=int32), array([  7,  17,  23, 582, 581], dtype=int32))


In [4]:
from collections import defaultdict
# import wrapper as wp
import time

start = time.time()
# there's almost certainly a way to do this in less than 0.1s, which costs us ~200 QPS
filter = ds.get_dataset_metadata()

rows, cols = filter.nonzero()
filter_dict = defaultdict(list)

for row, col in zip(rows, cols):
    filter_dict[row].append(col)
    
print(rows)
print(rows.shape)

print(cols)
print(cols.shape)

# # filters = [wp.QueryFilter(*filters[i]) for i in filters.keys()]
# filters = [None] * len(filter_dict.keys())
# for i in filter_dict.keys():
#     filters[i] = wp.QueryFilter(*filter_dict[i])

# print(f"Filter construction took {time.time() - start} seconds")

KeyboardInterrupt: 

In [15]:
print(ds.get_dataset().dtype.kind)
limit = 5
non_zero_column_indices = np.nonzero(ds.get_dataset_metadata()[0:limit])
print(non_zero_column_indices[0])
print(non_zero_column_indices[0][non_zero_column_indices[0]==4])

# Print the non-zero column indices for the first few rows for demonstration
for i in range(limit):
    row_indices = non_zero_column_indices[0][non_zero_column_indices[0] == i]
    col_indices = non_zero_column_indices[1][non_zero_column_indices[0] == i]
    print('row', row_indices)
    print('##', col_indices[0],col_indices[1])
    print(f"Row {i}: Non-zero column indices: {col_indices}")

u
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4]
[4 4 4]
row [0 0 0 0 0 0 0 0 0 0 0 0 0]
## 6 15
Row 0: Non-zero column indices: [  6  15  24  89 337 443 442 441 440 439 438 437 436]
row [1 1 1 1 1]
## 7 17
Row 1: Non-zero column indices: [  7  17  23 582 581]
row [2 2 2 2 2]
## 7 17
Row 2: Non-zero column indices: [  7  17  23 582 581]
row [3 3 3 3 3 3 3 3]
## 6 19
Row 3: Non-zero column indices: [  6  19  29 595 594 593 592 591]
row [4 4 4]
## 7 17
Row 4: Non-zero column indices: [ 7 17 24]


In [34]:
import numpy as np

# Sample data
a = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4])
n = 5
ret = []
    
    
def get_result(data, limit=10):
    non_zero_column_indices = np.nonzero(data[0:limit])
    ret = []
    n = data.shape[0]
    for idx in range(n):
        ret.append(non_zero_column_indices[1][non_zero_column_indices[0] == idx])
    return ret

start = time.time()
val = get_result(ds.get_dataset_metadata(),1000000)
print(f"Filter construction took {time.time() - start} seconds")
# print(val.shape)
print(val[0])

Filter construction took 0.5457053184509277 seconds
[  6  15  24  89 337 443 442 441 440 439 438 437 436]


In [1]:
print(ds.get_queries().shape)
print(ds.get_queries_metadata().shape)

queries = ds.get_queries()
q_metadata = ds.get_queries_metadata()
print(np.nonzero(q_metadata[0]))
print(np.nonzero(q_metadata[10]))
print(q_metadata[10])



non_zero_column_indices = np.nonzero(ds.get_queries_metadata())

# Print the non-zero column indices for the first few rows for demonstration
for i in range(100):
    row_indices = non_zero_column_indices[0][non_zero_column_indices[0] == i]
    col_indices = non_zero_column_indices[1][non_zero_column_indices[0] == i]
    print(f"Row {i}: Non-zero column indices: {col_indices}")

NameError: name 'ds' is not defined

In [33]:
import numpy as np

def get_result(data, limit=10):
    # Find non-zero column indices for the first 'limit' rows
    non_zero_column_indices = np.nonzero(data[:limit])
    
    # Create an array of row indices
    row_indices = np.arange(data.shape[0])
    
    # Use broadcasting to compare row indices with non-zero row indices
    matches = non_zero_column_indices[0][:, np.newaxis] == row_indices
    
    # Transpose the boolean mask to match the shape of non_zero_column_indices[1]
    matches = matches.T
    
    # Use boolean masking to extract matching column indices
    result = [non_zero_column_indices[1][match] for match in matches]
    
    return result

# Example usage
start = time.time()
result = get_result(ds.get_dataset_metadata()[0:1000000] , limit=1000000)
print(f"Filter construction took {time.time() - start} seconds")
print(result[0])


MemoryError: Unable to allocate 7.98 TiB for an array with shape (8776663, 1000000) and data type bool

In [1]:
import os
import numpy as np
import time
import sys

from neurips23.filter.base import BaseFilterANN
from benchmark.datasets import DATASETS
import pgvector.psycopg
import pgvector.asyncpg
import psycopg
from pprint import pprint
from dotenv import load_dotenv

In [3]:
socket_dir = "/var/run/postgresql"
query = "SELECT id FROM items LIMIT  %s"
conn = psycopg.connect(user="ann", password="ann", dbname="ann", autocommit=True, host=socket_dir)
pgvector.psycopg.register_vector(conn)
cur = conn.cursor()

In [17]:
query = "SELECT id FROM items where ARRAY[%s]::integer[] <@ tags ORDER BY embedding <-> %s LIMIT %s"
k = 5
vec = [155, 73, 118, 142, 133, 123, 147, 76, 154, 122, 143, 107, 127, 130, 95, 116, 115, 129, 90, 82, 179, 112, 101, 126, 146, 126, 152, 98, 131, 152, 118, 119, 103, 130, 124, 103, 107, 137, 108, 120, 86, 124, 130, 76, 112, 99, 142, 106, 145, 119, 119, 123, 103, 124, 178, 84, 159, 107, 109, 94, 154, 115, 135, 122, 108, 144, 136, 134, 113, 125, 159, 152, 163, 138, 92, 96, 141, 166, 127, 119, 117, 153, 116, 147, 124, 122, 106, 152, 119, 132, 99, 153, 132, 134, 93, 149, 147, 104, 149, 154, 100, 164, 118, 107, 88, 144, 116, 195, 130, 94, 125, 126, 105, 115, 123, 132, 157, 166, 119, 173, 134, 109, 99, 107, 130, 153, 174, 145, 147, 102, 126, 132, 125, 110, 98, 155, 146, 121, 133, 140, 131, 110, 151, 100, 204, 146, 133, 102, 134, 141, 150, 165, 114, 103, 146, 77, 112, 127, 132, 94, 81, 163, 146, 146, 116, 103, 130, 145, 190, 175, 150, 68, 133, 103, 106, 129, 150, 71, 134, 123, 113, 123, 139, 151, 135, 144, 140, 139, 148, 150, 121, 130]
cur.execute(query, ([28],str(vec),k) ,binary=True, prepare=True)
result = [id for id, in cur.fetchall()]
print(result)

UndefinedFunction: operator does not exist: vector <-> smallint[]
LINE 1: ...e ARRAY[$1]::integer[] <@ tags ORDER BY embedding <-> $2 LIM...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.