In [3]:
import pdb
import pickle
import numpy as np
import os
from benchmark.datasets import DATASETS
from benchmark.dataset_io import download_accelerated

In [8]:
ds = DATASETS['yfcc-10M']()

In [24]:
print(ds.get_dataset().shape)
print(ds.get_dataset_metadata().shape)
# print(ds.get_dataset_metadata()[1:2,:])

val = ds.get_dataset_metadata()[0]
print(np.nonzero(val))
print(np.nonzero(ds.get_dataset_metadata()[1]))

(10000000, 192)
(10000000, 200386)
(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32), array([  6,  15,  24,  89, 337, 443, 442, 441, 440, 439, 438, 437, 436],
      dtype=int32))
(array([0, 0, 0, 0, 0], dtype=int32), array([  7,  17,  23, 582, 581], dtype=int32))


In [34]:
non_zero_column_indices = np.nonzero(ds.get_dataset_metadata())

# Print the non-zero column indices for the first few rows for demonstration
for i in range(100):
    row_indices = non_zero_column_indices[0][non_zero_column_indices[0] == i]
    col_indices = non_zero_column_indices[1][non_zero_column_indices[0] == i]
    print('row', row_indices)
    print('##', col_indices[0],col_indices[1])
    print(f"Row {i}: Non-zero column indices: {col_indices}")

## 6 15
Row 0: Non-zero column indices: [  6  15  24  89 337 443 442 441 440 439 438 437 436]
## 7 17
Row 1: Non-zero column indices: [  7  17  23 582 581]
## 7 17
Row 2: Non-zero column indices: [  7  17  23 582 581]
## 6 19
Row 3: Non-zero column indices: [  6  19  29 595 594 593 592 591]
## 7 17
Row 4: Non-zero column indices: [ 7 17 24]
## 8 18
Row 5: Non-zero column indices: [ 8 18 29]
## 3 18
Row 6: Non-zero column indices: [  3  18  33 820 819]
## 8 16
Row 7: Non-zero column indices: [ 8 16]
## 2 15
Row 8: Non-zero column indices: [  2  15  23  89 335 928 927 926 925 924 923 392]
## 5 13
Row 9: Non-zero column indices: [  5  13  36 952]
## 8 19
Row 10: Non-zero column indices: [ 8 19 29]
## 7 19
Row 11: Non-zero column indices: [ 7 19 24]
## 7 11
Row 12: Non-zero column indices: [   7   11   29 1000  999  998  997  996  995  994  993  992  991  990
  989  988  987  986  985  984  983  982  981  980  979  978  977  976
  975  974  973  932  890  833  832  831]
## 4 13
Row 13: Non

IndexError: index 1 is out of bounds for axis 0 with size 1

In [31]:
print(ds.get_queries().shape)
print(ds.get_queries_metadata().shape)

queries = ds.get_queries()
q_metadata = ds.get_queries_metadata()
print(np.nonzero(q_metadata[0]))
print(np.nonzero(q_metadata[10]))
print(q_metadata[10])



non_zero_column_indices = np.nonzero(ds.get_queries_metadata())

# Print the non-zero column indices for the first few rows for demonstration
for i in range(100):
    row_indices = non_zero_column_indices[0][non_zero_column_indices[0] == i]
    col_indices = non_zero_column_indices[1][non_zero_column_indices[0] == i]
    print(f"Row {i}: Non-zero column indices: {col_indices}")

(100000, 192)
(100000, 200386)
(array([0], dtype=int32), array([28], dtype=int32))
(array([0], dtype=int32), array([2], dtype=int32))
  (0, 2)	1.0
Row 0: Non-zero column indices: [28]
Row 1: Non-zero column indices: [851 769]
Row 2: Non-zero column indices: [108757]
Row 3: Non-zero column indices: [5692 2212]
Row 4: Non-zero column indices: [1447   23]
Row 5: Non-zero column indices: [2169]
Row 6: Non-zero column indices: [90]
Row 7: Non-zero column indices: [3432 3075]
Row 8: Non-zero column indices: [3805  414]
Row 9: Non-zero column indices: [7616  426]
Row 10: Non-zero column indices: [2]
Row 11: Non-zero column indices: [35]
Row 12: Non-zero column indices: [28]
Row 13: Non-zero column indices: [4736]
Row 14: Non-zero column indices: [3975]
Row 15: Non-zero column indices: [1871 1515]
Row 16: Non-zero column indices: [25]
Row 17: Non-zero column indices: [35]
Row 18: Non-zero column indices: [2]
Row 19: Non-zero column indices: [95]
Row 20: Non-zero column indices: [4839 1119]
Row